config/routes.rb
ShoppyCartus::Engine.routes.draw do
  root to: 'order_items#index'
  resources :orders do
    get '/confirm/:token', to: 'orders#confirm', as: 'confirm'
  end
  resources :order_steps, only: %i[index show update]
  resources :order_items, except: %i[new edit show]
  resources :coupons, only: %i[create destroy]
end

app/models/shoppy_cartus/ability.rb
# frozen_string_literal: true

module ShoppyCartus
  class Ability
    include CanCan::Ability

    def initialize(user, order)
      user ||= ShoppyCartus.user_class.constantize.new

      can :manage, OrderItem, order_id: order.id
      can :manage, Coupon, order_id: order.id
      can %i[index show confirm], Order, user_id: user.id
      can %i[create update], CreditCard, user_id: user.id
    end
  end
end

app/models/shoppy_cartus/address.rb
module ShoppyCartus
  class Address < ApplicationRecord
    belongs_to :addressable, polymorphic: true
    validates :first_name, :last_name, :address, :city, :zip, :country, :phone, :kind, presence: true
    enum kind: %i[billing shipping]
  end
end

app/models/shoppy_cartus/application_record.rb
module ShoppyCartus
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/shoppy_cartus/coupon.rb
module ShoppyCartus
  class Coupon < ApplicationRecord
    belongs_to :order, optional: true, class_name: 'ShoppyCartus::Order'
    validates :code, :sale, presence: true
  end
end

app/models/shoppy_cartus/credit_card.rb
module ShoppyCartus
  class CreditCard < ApplicationRecord
    has_many :orders, dependent: :nullify, class_name: 'ShoppyCartus::Order'
    belongs_to :user, class_name: ShoppyCartus.user_class
    validates :number, :cvv, :expiration_date, :card_name, presence: true
    validates :number, format: { with: /\A\d{16}\z/ }
    validates :cvv, format: { with: /\A\d{3,4}\z/ }
    validates :expiration_date, format: { with: /\A(\d{2})\/(\d{2})\z/ }
    validates :card_name, format: { with: /\A[a-zA-Z]{,50}\z/ }
  end
end

app/models/shoppy_cartus/delivery.rb
module ShoppyCartus
  class Delivery < ApplicationRecord
    has_many :orders, dependent: :nullify, class_name: 'ShoppyCartus::Order'
    validates :title, :days, :price, presence: true
  end
end

app/models/shoppy_cartus/order.rb
module ShoppyCartus
  class Order < ApplicationRecord
    include AASM
    belongs_to :user, optional: true, class_name: ShoppyCartus.user_class
    belongs_to :credit_card, optional: true, class_name: 'ShoppyCartus::CreditCard'
    belongs_to :delivery, optional: true, class_name: 'ShoppyCartus::Delivery'
    has_many :addresses, as: :addressable, dependent: :destroy
    has_many :order_items, dependent: :destroy, class_name: 'ShoppyCartus::OrderItem'
    has_one :coupon, dependent: :nullify, class_name: 'ShoppyCartus::Coupon'
    validates :state, presence: true
    scope :in_progress, -> { find_by(state: 'filling') }
    scope :executed, -> { where.not(state: 'filling') }
    scope :by_state, ->(state) { where(state: state) }
    accepts_nested_attributes_for :addresses

    aasm column: :state do
      state :filling, initial: true
      state :in_confirmation, after_enter: :send_confirmation
      state :in_processing
      state :in_delivery
      state :completed
      state :canceled

      event :confirm do
        transitions from: :filling, to: :in_confirmation
      end

      event :process do
        transitions from: :in_confirmation, to: :in_processing
      end

      event :deliver do
        transitions from: :in_processing, to: :in_delivery
      end

      event :complete do
        transitions from: :in_delivery, to: :completed
      end

      event :cancel do
        transitions from: %i[filling in_confirmation in_processing in_delivery completed], to: :canceled
      end
    end

    def send_confirmation
      ShoppyCartus::OrderMailer.confirm_order(user, self).deliver_now
    end

    def self.aasm_states
      aasm.states.map(&:name)
    end

    def self.active_order_for_user(user)
      find_by(user: user, state: 'filling')
    end
  end
end

app/models/shoppy_cartus/order_item.rb
module ShoppyCartus
  class OrderItem < ApplicationRecord
    belongs_to :order, class_name: 'ShoppyCartus::Order'
    belongs_to :product, class_name: ShoppyCartus.product_class
    validates :price, :quantity, presence: true
  end
end

app/controllers/shoppy_cartus/application_controller.rb
module ShoppyCartus
  class ApplicationController < ShoppyCartus.parent_controller.constantize
    before_action :set_order, :set_locale, :current_ability

    [CanCan::AccessDenied, ActiveRecord::RecordNotFound, ActionController::RoutingError].each do |error|
      rescue_from error do |exception|
        redirect_to order_items_path, alert: exception.message
      end
    end

    define_method "authenticate_#{ShoppyCartus.user_class.downcase}!" do
      return if current_user
      redirect_to order_items_path, alert: t('checkout.authorize')
    end

    def current_order
      ShoppyCartus::Order.find_by(id: session[:order_id]) || ShoppyCartus::Order.active_order_for_user(current_user) || new_session_order
    end

    def current_ability
      @current_ability ||= Ability.new(current_user, current_order)
    end

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

    def default_url_options(*)
      { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
    end

    private

    def set_order
      @order ||= current_order.decorate
    end

    def new_session_order
      order = ShoppyCartus::Order.create(user: current_user)
      session[:order_id] = order.id
      order
    end
  end
end

app/controllers/shoppy_cartus/coupons_controller.rb
# frozen_string_literal: true

module ShoppyCartus
  class CouponsController < ApplicationController
    authorize_resource class: 'ShoppyCartus::Coupon'

    def create
      coupon = ShoppyCartus::Coupon.find_by(code: coupon_params[:code])
      return redirect_to order_items_path, alert: t('coupon.not_exist') unless coupon
      return redirect_to order_items_path, alert: t('coupon.used') if coupon.order
      @order.update(coupon: coupon)
      redirect_to order_items_path, notice: t('coupon.added')
    end

    def destroy
      @order.coupon.update(order_id: nil)
      redirect_to order_items_path, notice: t('coupon.removed')
    end

    private

    def coupon_params
      params.require(:coupon).permit(:code)
    end
  end
end

app/controllers/shoppy_cartus/order_items_controller.rb
require_dependency 'shoppy_cartus/application_controller'

module ShoppyCartus
  class OrderItemsController < ApplicationController
    load_and_authorize_resource class: 'ShoppyCartus::OrderItem'

    def index
      @items = @order.order_items.map(&:decorate) if @order.order_items.any?
    end

    def create
      if @order.order_items.where(product_id: order_items_params[:product_id]).any?
        return redirect_to order_items_path, alert: t('cart.alredy_added')
      end
      @order.order_items.create(order_items_params)
      redirect_to order_items_path, notice: t('cart.successful_added')
    end

    def update
      params[:increment] ? increment : decrement
      redirect_to order_items_path
    end

    def destroy
      @order_item.destroy
      redirect_to order_items_path, notice: t('cart.removed_successful')
    end

    private

    def order_items_params
      params.require(:order_items).permit(:price, :quantity, :product_id)
    end

    def increment
      return flash[:alert] = t('cart.no_more') if @order_item.quantity == @order_item.product.quantity
      @order_item.increment!(:quantity)
    end

    def decrement
      return flash[:alert] = t('cart.no_less') if @order_item.quantity == 1
      @order_item.decrement!(:quantity)
    end
  end
end

app/controllers/shoppy_cartus/order_steps_controller.rb
module ShoppyCartus
  class OrderStepsController < ApplicationController
    include Wicked::Wizard
    steps :address, :delivery, :payment, :confirm, :complete
    before_action "authenticate_#{ShoppyCartus.user_class.downcase}!".to_sym, :check_order, :relate_with_user,
                  :set_form, :set_needful_step

    def index
      redirect_to_step(@needful_step)
    end

    def show
      redirect_to_step(@needful_step) && return if wrong_step?
      render_wizard
      session[:order_id] = nil if step == :complete
    end

    def update
      redirect_to_step(next_step) && return if @form.update(step, order_params)
      render_wizard
    end

    private

    def check_order
      redirect_to order_items_path, alert: t('cart.empty') unless ShoppyCartus::OrderItem.where(order: @order).any?
    end

    def relate_with_user
      @order.update(user: current_user) unless @order.user
    end

    def set_form
      @form = ShoppyCartus::OrderStepsForm.new(@order)
    end

    def redirect_to_step(needful_step)
      redirect_to wizard_path(needful_step)
    end

    def wrong_step?
      (step != @needful_step) && step_index(step) > step_index(@needful_step)
    end

    def step_index(_step)
      wizard_steps.index(_step)
    end

    def set_needful_step
      @needful_step = @form.get_step
    end

    def order_params
      params.permit(
        :use_billing,
        :delivery,
        credit_card: %i[number cvv card_name expiration_date],
        billing_address:  %i[first_name last_name address city zip country phone kind],
        shipping_address: %i[first_name last_name address city zip country phone kind]
      )
    end
  end
end

app/controllers/shoppy_cartus/orders_controller.rb
module ShoppyCartus
  class OrdersController < ApplicationController
    before_action "authenticate_#{ShoppyCartus.user_class.downcase}!".to_sym
    # authorize_resource class: 'ShoppyCartus::Order'

    def index
      authorize! :index, ShoppyCartus::Order
      @orders = current_user.orders.executed
      @orders = @orders.by_state(params[:state].to_sym) if valid_state?
    end

    def show
      @_order = ShoppyCartus::Order.find_by(id: params[:id]).decorate
      authorize! :show, @_order.object
    end

    def confirm
      order = ShoppyCartus::Order.find_by(id: params[:order_id])
      if order.confirmation_token == params[:token]
        authorize! :confirm, order
        order.process
        order.save
        return redirect_to order_items_path, notice: t('order.confirmed')
      end
      redirect_to order_items_path, alert: t('order.wrong_token')
    end

    private

    def valid_state?
      ShoppyCartus::Order.aasm_states.include?(params[:state]&.to_sym)
    end
  end
end

app/helpers/shoppy_cartus/application_helper.rb
module ShoppyCartus
  module ApplicationHelper
  end
end

app/views/shoppy_cartus/order_items/index.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin Cart
  - if @order.order_items.any?
    .visible-xs
      - @items.each do |item|
        .general-cart-item.divider-lg-bottom.mb-30
          = link_to(order_item_path(item), method: :delete, class: 'close general-cart-close', 'aria-label': "Close") do
            %span{'aria-hidden': "true"} &times;
          %p.title= item.product.title
          %table.table
            %tr
              %td
                %span.in-grey-600 Price
              %td
                %span.font-16.in-gold-500= "€#{item.product.price}"
            %tr
              %td.vertical-middle
                %span.in-grey-600 Quantity
              %td
                .input-group
                  %a.input-link{href: "#"}
                    %i.fa.fa-minus.line-heaght-40
                  %input.form-control.quantity-input{type: "text", value: item.quantity}
                  %a.input-link{href: "#"}
                    %i.fa.fa-plus.line-heaght-40
            %tr
              %td
                %span.in-grey-600 SubTotal
              %td
                %span.font-16.in-gold-500= "€#{item.subtotal}"
    .hidden-xs
      %table.table.table-hover
        %tr.no-hover
          %th.col-pic.pl-0
            %span.in-grey-600 Product
          %th.col-title
          %th.col-price
            %span.in-grey-600 Price
          %th.col-quantity
            %span.in-grey-600 Quantity
          %th.col-total
            %span.in-grey-600 SubTotal
          %th.col-close
        - @items.each do |item|
          %tr
            %td
              %p.title= item.product.title
            %td
              %span.font-16.in-gold-500= "€#{item.product.price}"
            %td
              .input-group
                - if item.quantity > 1
                  = link_to order_item_path(item), method: :put, class: 'input-link' do
                    %i.fa.fa-minus.line-heaght-40
                %input.form-control.quantity-input{type: "text", value: item.quantity}
                - if item.quantity < item.product.quantity
                  = link_to order_item_path(item, increment: true), method: :put, class: 'input-link' do
                    %i.fa.fa-plus.line-heaght-40
            %td
              %span.font-16.in-gold-500= "€#{item.subtotal}"
            %td
              = link_to(order_item_path(item), method: :delete, class: 'close general-cart-close', 'aria-label': "Close") do
                %span{'aria-hidden': "true"} &times;
    .general-order-wrap
      .row
        .col-sm-4
          - if @order.coupon
            = link_to 'Remove Coupon', coupon_path(@order.coupon), class: 'btn btn-primary mr-5 mb-15', id: 'coupon-code-btn', method: :delete
          - else
            = simple_form_for(:coupon, url: coupons_path, method: :post) do |f|
              .input-group.general-input-group
                = f.input :code, placeholder: 'Enter Your Coupon Code', input_html: { class: 'mb-30' },
                  label_html: { class: 'input-label' }, label: 'Enter Your Coupon Code'
                %div
                  = f.button :submit, class: 'btn-primary mr-5 mb-15', value: 'Apply Coupon', id: 'coupon-code-btn'
        .col-sm-8
          .res-mr-200.text-center.general-text-right
            %p.in-gold-500.font-18 Order Summary
            %table.general-summary-table.general-summary-table-right.general-text-right
              %tr
                %td
                  %p.font-16 Subtotal:
                %td
                  %p.font-16= "€#{@order.subtotal}"
              %tr
                %td
                  %p.font-16 Coupon:
                %td
                  %p.font-16= "€#{@order.sale}"
              %tr
                %td
                  %strong.font-18 Order Total:
                %td
                  %strong.font-18= "€#{@order.total}"
            = link_to order_steps_path do
              %button.btn.btn-default.mb-20.visible-xs-inline-block Checkout
    = link_to 'Checkout', order_steps_path, class: 'btn btn-default mb-20 hidden-xs center-block col-sm-2'
  - else
    %h2= t('cart.empty')